'use client';
import { ArrowUpRight, Crosshair, Flag, MapPin, Navigation, Pause, Shield, Star, Sun, VolumeX } from 'lucide-react';
import { buildings, distance, missions, roads, type Game } from '@/lib/game/engine';
export function Minimap({ g }: { g: Game }) {
  const pos = (v: number) => `${(v + 100) / 2}%`;
  return <div className="map-wrap"><div className="map-top"><span>N</span><span>COASTLINE DISTRICT</span><Navigation size={11} /></div><div className="minimap" role="img" aria-label="Live city minimap showing your position, police, and mission destination"><div className="map-ocean" />{roads.map(r => <div key={r}><i className="map-road vertical" style={{ left: pos(r) }} /><i className="map-road horizontal" style={{ top: pos(r) }} /></div>)}{buildings.map((b, i) => <i key={i} className="map-building" style={{ left: pos(b.x - 10), top: pos(b.z - 10), width: '10%', height: '10%' }} />)}{g.police.filter(p => p.hp > 0 && g.wanted > 0).map((p, i) => <i key={i} className="map-police" style={{ left: pos(p.x), top: pos(p.z) }} />)}{g.target && <i className="map-target" style={{ left: pos(g.target.x), top: pos(g.target.z) }} />}<Navigation className="map-player" size={14} fill="currentColor" style={{ left: pos(g.x), top: pos(g.z), transform: `translate(-50%,-50%) rotate(${g.yaw * 180 / Math.PI - 45}deg)` }} /></div><div className="map-footer"><MapPin size={11} />{g.x > 55 ? 'Marina Promenade' : g.z < -35 ? 'Downtown' : 'Palm Avenue'}<span>SW</span></div></div>;
}
export default function Hud({ g, menu }: { g: Game; menu: (tab: string) => void }) {
  const mission = g.mission >= 0 ? missions[g.mission] : null;
  const near = g.car < 0 && g.cars.some(c => distance(c, g) < 6);
  return <div className="hud">
    <header className="game-header"><div className="wordmark">COASTLINE<span>HEAT<span className="brand-dot">.</span></span><small>OPEN WORLD · VOL. 01</small></div><div className="world-status"><span className="live-dot" />FREE ROAM<i /><Sun size={14} /><span>17:42</span><span className="weather">24°C</span></div><div className="top-actions"><button aria-label="Audio information" onClick={() => menu('audio')}><VolumeX size={17} /></button><button aria-label="Pause game" onClick={() => menu('pause')}><Pause size={17} /></button></div></header>
    <section className="player-stats" aria-label="Player status"><div className="wanted" aria-label={`Wanted level ${g.wanted} of 5`}>{Array.from({ length: 5 }, (_, i) => <Star key={i} size={20} fill={i < g.wanted ? 'currentColor' : 'transparent'} className={i < g.wanted ? 'wanted-active' : ''} />)}</div><div className="cash"><span>$</span>{g.cash.toLocaleString('en-US').padStart(6, '0')}</div><span className="cash-label">AVAILABLE CASH</span>{g.wanted > 0 && <div className="pursuit">{g.escape > 0 ? `EVADING · ${Math.ceil(12 - g.escape)}s` : 'POLICE PURSUIT'}</div>}</section>
    {g.started && <section className="objective"><div className="eyebrow"><span className="gold-dot" />{mission ? mission.tag : 'YOUR CITY. YOUR RULES.'}</div><h2>{mission ? mission.name : 'Make your own way.'}</h2><p>{mission ? g.mission === 2 && g.checkpoint ? 'Lose your wanted level to finish the job.' : mission.description : 'Explore the coast or pick up a job to earn your first payout.'}</p>{mission ? <div className="objective-meta"><span><Flag size={13} />{g.mission === 2 ? `${g.guards.filter(n => n.hp <= 0).length}/3 targets` : `${g.checkpoint}/${mission.points.length} checkpoints`}</span><b>{Math.floor(g.timer / 60)}:{String(Math.max(0, Math.floor(g.timer % 60))).padStart(2, '0')}</b></div> : <button className="text-action" onClick={() => menu('missions')}>View missions <ArrowUpRight size={15} /></button>}</section>}
    <div className="hud-bottom"><div className="left-instruments"><Minimap g={g} /><div className="vitals"><span><Shield size={12} />HEALTH</span><div className="health-track"><i style={{ width: `${g.health}%` }} /></div><b>{Math.ceil(g.health)}</b></div></div><div className="bottom-center">{g.started && <><div className="interaction"><kbd>{g.car >= 0 || near ? 'E' : 'M'}</kbd><span>{g.car >= 0 ? 'Exit vehicle' : near ? 'Enter vehicle' : 'Find your next mission'}</span></div><div className="location-title">{g.x > 55 ? 'Marina Promenade' : g.z < -35 ? 'Downtown' : 'Palm Avenue'}</div><span className="location-subtitle">COASTLINE, SAN PACIFICO</span></>}</div><div className="right-instruments">{g.car >= 0 ? <><span className="instrument-label">VELOCITY GT <span>SPORT</span></span><div className="speed">{String(Math.round(Math.abs(g.speed) * 3.6)).padStart(3, '0')}<span>KM/H</span></div><div className="speed-ticks">{Array.from({ length: 22 }, (_, i) => <i key={i} className={Math.abs(g.speed) / 2 > i ? 'active' : ''} />)}</div><div className="gear">GEAR <b>{g.speed < -1 ? 'R' : g.speed < 1 ? 'N' : Math.min(5, Math.ceil(g.speed / 9))}</b><span>RWD</span></div></> : <><Crosshair size={22} /><div className="ammo">{g.reload > 0 ? '…' : String(g.ammo).padStart(2, '0')}<span>/ 12</span></div><span className="instrument-label">{g.reload > 0 ? 'RELOADING' : 'SIDEARM · SEMI-AUTO'}</span></>}</div></div>
    {g.started && g.car < 0 && <div className="crosshair" aria-hidden="true">+</div>}
    {g.started && g.messageTime > 0 && <div className="game-notice" role="status">{g.message}</div>}
    <footer className="control-strip"><div><kbd>W A S D</kbd> Move / Drive <kbd>E</kbd> Enter / Exit <kbd>SHIFT</kbd> Sprint <kbd>SPACE</kbd> Handbrake</div><div><kbd>M</kbd> Missions <kbd>ESC</kbd> Pause</div></footer>
  </div>;
}
