import { test } from 'node:test';
import assert from 'node:assert/strict';
// Node's native TypeScript runner requires the explicit extension.
// @ts-ignore -- Node test runner resolves the TypeScript source directly.
import { blocked, createGame, interact, load, save, startMission, tick } from './engine.ts';
const input = () => ({ keys: new Set<string>(), pressed: new Set<string>(), fire: false });
const advance = (g: ReturnType<typeof createGame>, seconds: number, controls = input()) => { for (let i = 0; i < Math.ceil(seconds / .02); i++) tick(g, controls, .02); };
test('parked vehicle can be entered and exited safely', () => { const g = createGame(); interact(g); assert.equal(g.car, 0); assert.equal(g.wanted, 1); interact(g); assert.equal(g.car, -1); assert.equal(blocked(g.x, g.z), false); });
test('acceleration, braking, collision, and pause', () => { const g = createGame(); g.playing = true; interact(g); const i = input(); i.keys.add('KeyW'); advance(g, 1, i); assert.ok(g.speed > 15); assert.ok(g.z < 35); i.keys.clear(); i.keys.add('Space'); advance(g, 1, i); assert.ok(g.speed < 3); g.playing = false; const z = g.z; advance(g, 1, i); assert.equal(g.z, z); assert.ok(blocked(15, 45)); assert.ok(blocked(110, 0)); assert.equal(blocked(0, 0), false); });
test('delivery rewards once, persists, and can be replayed', () => { const g = createGame(); g.playing = true; g.car = 0; startMission(g, 0); g.x = 60; g.z = -60; advance(g, .02); assert.equal(g.mission, -1); assert.equal(g.cash, 750); assert.deepEqual(g.completed, [0]); advance(g, 1); assert.equal(g.cash, 750); });
test('race progresses through all checkpoints', () => { const g = createGame(); g.playing = true; g.car = 0; startMission(g, 1); for (const [x,z] of [[60,30],[60,-60],[-30,-60],[-30,30]]) { g.x = x; g.z = z; advance(g, .02); } assert.equal(g.cash, 1200); assert.equal(g.mission, -1); });
test('combat requires targets and police escape', () => { const g = createGame(); g.playing = true; startMission(g, 2); g.guards.forEach((n: { hp: number }) => n.hp = 0); g.wanted = 2; g.heat = 20; advance(g, .02); assert.equal(g.checkpoint, 1); assert.equal(g.cash, 0); g.wanted = 0; advance(g, .02); assert.equal(g.cash, 1800); assert.equal(g.mission, -1); });
test('mission timeout permits retry without reward', () => { const g = createGame(); g.playing = true; startMission(g, 0); g.timer = .01; advance(g, .02); assert.equal(g.mission, -1); assert.equal(g.cash, 0); startMission(g, 0); assert.equal(g.mission, 0); assert.equal(g.timer, 100); });
test('aimed shots hit a guard and reload restores magazine', () => { const g = createGame(); g.playing = true; g.x = -3; g.z = -17; g.yaw = 0; const i = input(); i.fire = true; advance(g, .3, i); assert.equal(g.guards[0].hp, 0); assert.equal(g.ammo, 10); i.fire = false; i.pressed.add('KeyR'); advance(g, 1.5, i); assert.equal(g.ammo, 12); });
test('police can be evaded and health loss stops gameplay', () => { const g = createGame(); g.playing = true; g.wanted = 1; g.police.forEach((n: { hp: number }) => n.hp = 0); advance(g, 12.1); assert.equal(g.wanted, 0); g.health = 0; advance(g, .02); assert.equal(g.dead, true); assert.equal(g.playing, false); });
test('police make sustained progress across intersections', () => { const g = createGame(); g.playing = true; g.wanted = 1; g.heat = 100; const before = Math.hypot(g.police[0].x - g.x, g.police[0].z - g.z); advance(g, 7); const after = Math.hypot(g.police[0].x - g.x, g.police[0].z - g.z); assert.ok(after < before - 40, `Police should approach: ${before} → ${after}`); });
test('local saves round trip and malformed saves are safe', () => { const store = new Map<string,string>(); Object.defineProperty(globalThis, 'localStorage', { configurable: true, value: { setItem: (k: string,v: string) => store.set(k,v), getItem: (k: string) => store.get(k) ?? null } }); const g = createGame(); g.cash = 750; g.completed = [0]; g.quality = 'low'; save(g); const restored = createGame(); load(restored); assert.equal(restored.cash, 750); assert.equal(restored.quality, 'low'); assert.deepEqual(restored.completed, [0]); store.set('coastline-heat-v1', '{broken'); assert.doesNotThrow(() => load(createGame())); });
